version: '3.8'

services:
  task-management:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped 