apiVersion: v1
kind: Service
metadata:
  name: taskmanagement
spec:
  type: LoadBalancer
  selector:
    app: taskmanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080